apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  APP_NAME: "javalin-api"
  ENV: "localstack"
  AWS_ACCESS_KEY_ID: "test"
  AWS_SECRET_ACCESS_KEY: "test"
  AWS_REGION: "eu-west-1"
  OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
  OTEL_TRACES_EXPORTER: "otlp"
  OTEL_METRICS_EXPORTER: "prometheus"
  OTEL_METRICS_EXEMPLAR_FILTER: "always_off"
  OTEL_EXPORTER_PROMETHEUS_HOST: "0.0.0.0"
  OTEL_EXPORTER_PROMETHEUS_PORT: "9464"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://alloy.monitoring:4317"
