apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: iskaypet
namePrefix: javalin-api--
generatorOptions:
  disableNameSuffixHash: true
resources:
- config.yaml
- deployment.yaml
- hpa.yaml
- ingress.yaml
- namespace.yaml
- pdb.yaml
- service.yaml
labels:
- includeSelectors: true
  pairs:
    app: javalin-api
